version: '3'
services:
  db:
    container_name: mysqlDB
    image: mysql:latest
    environment:
      MYSQL_ROOT_NAME: root
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
