spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql


  datasource:
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.219.44:3306/dev


  security:
    user:
      password: 1
    oauth2:
      client:
        registration:
          naver:
            client-id: 5SbYJkRiYLcA1ocRyUhw
            client-secret: zyF8iAsGRl
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile
            client-name: Naver


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

