spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql


  datasource:
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver


    # github actions를 사용할 때는 en0와 같이 외부 ip로 접속을 하는 것이 아니고
    # github actions 내부에서 mysql을 pull하고, connect를 하기 때문에 db명을 적어주어야 한다.
    # 외부ip에서 docker로 접속하는 것이 아닌 내부끼리 접속을 함
    # 192.168.0.7
    url: jdbc:mysql://192.168.0.7:3306/dev


  security:
    user:
      password: 1
    oauth2:
      client:
        registration:
          naver:
            client-id: 5SbYJkRiYLcA1ocRyUhw
            client-secret: zyF8iAsGRl
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile
            client-name: Naver


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# 또 다른 yml을 사용하려면 이런식으로 작성해야 한다.
  profiles:
    active: jwt