spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql


  datasource:
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver


    # github actions를 사용할 때는 en0와 같이 외부 ip로 접속을 하는 것이 아니고
    # github actions 내부에서 mysql을 pull하고, connect를 하기 때문에 db명을 적어주어야 한다.
    # 외부ip에서 docker로 접속하는 것이 아닌 내부끼리 접속을 함
    # 192.168.0.7
    url: jdbc:mysql://192.168.219.48:3306/dev

# 또 다른 yml을 사용하려면 이런식으로 작성해야 한다.
  profiles:
    active: oauth2, jwt
