name: Build and Deploy Spring App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # 최신 버전으로 변경
        with:
          java-version: '17'
          distribution: 'openjdk'     # OpenJDK 배포판

      - name: Build the project with Gradle
        run: ./gradlew build  # Gradle로 프로젝트 빌드

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 비밀번호

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/in-continue-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/in-continue-dev:latest
          

  # Deploy step is omitted for local testing
