name: Build and Deploy Spring App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행!

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest  # MySQL 이미지 사용
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: dev  # 데이터베이스 이름 수정
#          MYSQL_USER: root  # 기본 사용자 설정
#          MYSQL_PASSWORD: admin1234  # 기본 비밀번호 설정
        ports:
          - 3306:3306  # 포트 매핑
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Temurin 배포판으로 변경

      - name: Build the project with Gradle
        run: ./gradlew build  # Gradle로 프로젝트 빌드

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 비밀번호

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/in-continue-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/in-continue-dev:latest
